"""Tests for uv-workspace integration."""

from __future__ import annotations

from pathlib import Path

from conftest import make_repo_with_file
from reporoot.integrations.base import IntegrationContext
from reporoot.integrations.uv_workspace import UvWorkspace


def _ctx(workspace: Path, repos: dict[str, dict], config: dict | None = None) -> IntegrationContext:
    return IntegrationContext(root=workspace, project="test", repos=repos, config=config or {})


class TestUvWorkspaceActivate:
    def test_generates_pyproject_toml(self, workspace: Path):
        make_repo_with_file(
            workspace, "github/a/svc", "pyproject.toml",
            '[project]\nname = "svc"\nversion = "0.1.0"\n',
        )
        make_repo_with_file(
            workspace, "github/a/lib", "pyproject.toml",
            '[project]\nname = "lib"\nversion = "0.1.0"\n',
        )

        repos = {
            "github/a/svc": {"type": "git", "url": "https://github.com/a/svc.git", "version": "main"},
            "github/a/lib": {"type": "git", "url": "https://github.com/a/lib.git", "version": "main"},
        }

        UvWorkspace().activate(_ctx(workspace, repos))

        pyproject = (workspace / "pyproject.toml").read_text()
        assert "Generated by reporoot" in pyproject
        assert "[tool.uv.workspace]" in pyproject
        assert '"github/a/lib"' in pyproject
        assert '"github/a/svc"' in pyproject

    def test_skips_repos_without_pyproject(self, workspace: Path):
        make_repo_with_file(
            workspace, "github/a/svc", "pyproject.toml",
            '[project]\nname = "svc"\n',
        )
        repo_dir = workspace / "github" / "a" / "web"
        repo_dir.mkdir(parents=True)

        repos = {
            "github/a/svc": {"type": "git", "url": "https://github.com/a/svc.git", "version": "main"},
            "github/a/web": {"type": "git", "url": "https://github.com/a/web.git", "version": "main"},
        }

        UvWorkspace().activate(_ctx(workspace, repos))

        pyproject = (workspace / "pyproject.toml").read_text()
        assert '"github/a/svc"' in pyproject
        assert "web" not in pyproject

    def test_removes_when_no_python_repos(self, workspace: Path):
        (workspace / "pyproject.toml").write_text("# old")

        UvWorkspace().activate(_ctx(workspace, {}))
        assert not (workspace / "pyproject.toml").exists()

    def test_deactivate_removes_file(self, workspace: Path):
        (workspace / "pyproject.toml").write_text("# Generated by reporoot\n")
        UvWorkspace().deactivate(workspace)
        assert not (workspace / "pyproject.toml").exists()

    def test_deactivate_noop_if_missing(self, workspace: Path):
        UvWorkspace().deactivate(workspace)  # should not raise
