"""cargo-workspace integration — generate root Cargo.toml with workspace members."""

from __future__ import annotations

from pathlib import Path

from reporoot.integrations.base import IntegrationContext, Issue

_FILE = "Cargo.toml"
_HEADER = "# Generated by reporoot — do not edit\n"


class CargoWorkspace:
    name = "cargo-workspace"
    default_enabled = True

    def activate(self, ctx: IntegrationContext) -> None:
        active = ctx.active_repos()
        cargo_paths: list[str] = []
        for repo_path in sorted(active):
            repo_dir = ctx.root / repo_path
            if repo_dir.is_dir() and (repo_dir / _FILE).exists():
                cargo_paths.append(repo_path)

        target = ctx.root / _FILE
        if cargo_paths:
            members = ", ".join(f'"{p}"' for p in cargo_paths)
            content = (
                f"{_HEADER}\n"
                f"[workspace]\n"
                f"members = [{members}]\n"
                f"resolver = \"2\"\n"
            )
            target.write_text(content)
            print(f"  wrote {_FILE} ({len(cargo_paths)} crates)")
        else:
            self._remove(target)

    def deactivate(self, root: Path) -> None:
        target = root / _FILE
        if target.exists():
            # Only remove if we generated it
            content = target.read_text()
            if content.startswith(_HEADER):
                target.unlink()
                print(f"  removed {_FILE}")

    def check(self, ctx: IntegrationContext) -> list[Issue]:  # noqa: ARG002
        return []

    def _remove(self, path: Path) -> None:
        if path.exists():
            content = path.read_text()
            if content.startswith(_HEADER):
                path.unlink()
                print(f"  removed {path.name}")
