"""claude-md integration — generate CLAUDE.md for AI agent context."""

from __future__ import annotations

from pathlib import Path

from reporoot.integrations.base import IntegrationContext, Issue

_FILE = "CLAUDE.md"
_HEADER = "<!-- Generated by reporoot — do not edit -->"


def _generate_content(ctx: IntegrationContext) -> str:
    """Build the CLAUDE.md content from project state."""
    from reporoot.workspace import project_fetch_source

    lines = [_HEADER, ""]

    # Overview
    lines.append(
        "This is a [reporoot](https://cwalv.github.io/reporoot/) workspace — "
        "multiple repos under one directory tree, wired into ecosystem workspaces "
        "(npm, Go, uv, etc.) so cross-repo imports resolve locally. "
        "Each repo is a normal git clone; the project file declares which repos "
        "belong together."
    )
    lines.append("")

    # Active project
    lines.append(f"Active project: **{ctx.project}** (`projects/{ctx.project}/`)")
    source = project_fetch_source(ctx.root, ctx.project)
    if source:
        lines.append(f"Reproduce: `reporoot fetch {source}`")
    lines.append("")

    # What is a project
    lines.append(
        "A **project** is a named group of repos with a `reporoot.yaml` file "
        "declaring which repos belong together and their roles. "
        "Project docs and coordination live in `projects/{name}/`; "
        "code repos live at `{registry}/{owner}/{repo}/`. "
        "One project is active at a time — it determines which repos are "
        "wired into workspace files."
    )
    lines.append("")

    # Key commands
    lines.append("## Commands")
    lines.append("")
    lines.append("- `reporoot` — show active project and fetch source")
    lines.append("- `reporoot activate <project>` — switch projects, regenerate workspace files")
    lines.append("- `reporoot add <url>` — clone a repo and add to active project")
    lines.append("- `reporoot check` — find convention violations (orphans, missing roles, stale locks)")
    lines.append("")

    # Repo table
    if ctx.repos:
        lines.append("## Repos")
        lines.append("")
        lines.append("| Path | Role | Note |")
        lines.append("|------|------|------|")
        for repo_path in sorted(ctx.repos):
            info = ctx.repos[repo_path]
            role = info.get("role", "")
            note = info.get("note", "")
            lines.append(f"| `{repo_path}` | {role} | {note} |")
        lines.append("")

    # Roles reference
    lines.append(
        "Roles indicate change resistance: "
        "**primary** (change freely), "
        "**fork** (prefer upstreaming), "
        "**dependency** (needs upstream acceptance), "
        "**reference** (read-only, no local changes)."
    )
    lines.append("")

    return "\n".join(lines)


class ClaudeMd:
    name = "claude-md"
    default_enabled = True

    def activate(self, ctx: IntegrationContext) -> None:
        content = _generate_content(ctx)
        target = ctx.root / _FILE
        target.write_text(content)
        print(f"  wrote {_FILE} ({len(ctx.repos)} repos)")

    def deactivate(self, root: Path) -> None:
        target = root / _FILE
        if target.is_file() and not target.is_symlink():
            # Only remove if it's our generated file
            text = target.read_text()
            if text.startswith(_HEADER):
                target.unlink()
                print(f"  removed {_FILE}")

    def check(self, ctx: IntegrationContext) -> list[Issue]:
        issues: list[Issue] = []
        target = ctx.root / _FILE
        if not target.exists():
            issues.append(
                Issue(
                    integration=self.name,
                    message=f"{_FILE} missing at workspace root",
                )
            )
        elif target.is_file():
            text = target.read_text()
            if not text.startswith(_HEADER):
                issues.append(
                    Issue(
                        integration=self.name,
                        message=f"{_FILE} exists but was not generated by reporoot (missing header)",
                        level="warning",
                    )
                )
        return issues
