"""claude-md integration — generate CLAUDE.md for AI agent context."""

from __future__ import annotations

from pathlib import Path

from reporoot.integrations.base import IntegrationContext, Issue

_FILE = "CLAUDE.md"
_HEADER = "<!-- Generated by reporoot — do not edit -->"


def _generate_content(ctx: IntegrationContext) -> str:
    """Build the CLAUDE.md content from project state."""
    from reporoot.workspace import project_fetch_source

    lines = [_HEADER, ""]
    lines.append(f"This is a [reporoot](https://github.com/cwalv/reporoot) workspace.")
    lines.append(f"Active project: **{ctx.project}**")

    source = project_fetch_source(ctx.root, ctx.project)
    if source:
        lines.append(f"Fetch source: `reporoot fetch {source}`")

    lines.append(f"Project directory: `projects/{ctx.project}/`")
    lines.append("")

    # Repo table
    if ctx.repos:
        lines.append("## Repos")
        lines.append("")
        lines.append("| Path | Role | Note |")
        lines.append("|------|------|------|")
        for repo_path in sorted(ctx.repos):
            info = ctx.repos[repo_path]
            role = info.get("role", "")
            # Extract inline comment if present (stored during YAML parsing)
            note = info.get("note", "")
            lines.append(f"| `{repo_path}` | {role} | {note} |")
        lines.append("")

    # Roles reference
    lines.append("## Roles")
    lines.append("")
    lines.append("- **primary** — our code, change freely")
    lines.append("- **fork** — forked upstream, prefer upstreaming changes")
    lines.append("- **dependency** — code we build against, changes need upstream acceptance")
    lines.append("- **reference** — cloned for reading/study, no local changes")
    lines.append("")

    return "\n".join(lines)


class ClaudeMd:
    name = "claude-md"
    default_enabled = True

    def activate(self, ctx: IntegrationContext) -> None:
        content = _generate_content(ctx)
        target = ctx.root / _FILE
        target.write_text(content)
        print(f"  wrote {_FILE} ({len(ctx.repos)} repos)")

    def deactivate(self, root: Path) -> None:
        target = root / _FILE
        if target.is_file() and not target.is_symlink():
            # Only remove if it's our generated file
            text = target.read_text()
            if text.startswith(_HEADER):
                target.unlink()
                print(f"  removed {_FILE}")

    def check(self, ctx: IntegrationContext) -> list[Issue]:
        issues: list[Issue] = []
        target = ctx.root / _FILE
        if not target.exists():
            issues.append(
                Issue(
                    integration=self.name,
                    message=f"{_FILE} missing at workspace root",
                )
            )
        elif target.is_file():
            text = target.read_text()
            if not text.startswith(_HEADER):
                issues.append(
                    Issue(
                        integration=self.name,
                        message=f"{_FILE} exists but was not generated by reporoot (missing header)",
                        level="warning",
                    )
                )
        return issues
