"""uv-workspace integration — generate root pyproject.toml with uv workspace members."""

from __future__ import annotations

import shutil
from pathlib import Path

from reporoot.integrations.base import IntegrationContext, Issue
from reporoot.integrations.run import run_tool

_FILE = "pyproject.toml"


class UvWorkspace:
    name = "uv-workspace"
    default_enabled = True

    def activate(self, ctx: IntegrationContext) -> None:
        active = ctx.active_repos()
        py_paths: list[str] = []
        for repo_path in sorted(active):
            repo_dir = ctx.root / repo_path
            if repo_dir.is_dir() and (repo_dir / "pyproject.toml").exists():
                py_paths.append(repo_path)

        target = ctx.root / _FILE
        if py_paths:
            members = "\n".join(f'    "{p}",' for p in py_paths)
            content = f"# Generated by reporoot — do not edit\n[tool.uv.workspace]\nmembers = [\n{members}\n]\n"
            target.write_text(content)
            print(f"  wrote {_FILE} ({len(py_paths)} workspace members)")
            uv = shutil.which("uv")
            if uv:
                run_tool([uv, "sync"], cwd=ctx.root)
        else:
            self._remove(target)

    def deactivate(self, root: Path) -> None:
        self._remove(root / _FILE)

    def check(self, ctx: IntegrationContext) -> list[Issue]:
        issues: list[Issue] = []
        py_paths = [p for p in ctx.repos if (ctx.root / p).is_dir() and (ctx.root / p / "pyproject.toml").exists()]
        if py_paths and not shutil.which("uv"):
            issues.append(
                Issue(
                    integration=self.name,
                    message="uv not found on PATH (needed for uv workspaces)",
                )
            )
        return issues

    def _remove(self, path: Path) -> None:
        if path.exists():
            path.unlink()
            print(f"  removed {path.name}")
